version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-217-225-16.eu-west-1.compute.amazonaws.com
            database: d1akhhe7tgir5p
            # schema: public
            user: xdskdbxxtbpfef
            password: 78af6e81496bcc29ca73f77551db8a2f8af781217af7d8730de5fdde95ac5e12
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true